ALTER TABLE LineAlba
ADD 
    SOL_CosteAnterior money NULL,
    SOL_MODCOSTESADICIONALES char(1) NULL
        CONSTRAINT CK_LineAlba_SOL_MODCOSTESADICIONALES
        CHECK (SOL_MODCOSTESADICIONALES IN ('T','F') OR SOL_MODCOSTESADICIONALES IS NULL);